---
title: "Justin Sub-analysis"
author: "Justin Hsie"
date: "11/30/2018"
output: github_document
---

##How are successes distributed by insurance status?

Measure success with SSI. Variables are postop_ssi_super, postop_ssi_deep, and postop_ssi_organspace

####Setup

```{r, message = FALSE}
library(tidyverse)
library(haven)
```

####Clean data

```{r data-import }
colectomies = read_dta("colectomy_raw_new.dta")
```

```{r data-reduction }
is_mostly_intact = function(col) {
  # Account for literal NAs and blanks
  missings = is.na(col) | col == "" | col == "NA"
  return(sum(missings) <= (3084 / 2))
}

tidy_colectomies = colectomies %>% 
  select(-starts_with("flg_"), -starts_with("e_")) %>% 
  select_if(unlist(map(., is_mostly_intact), use.names = FALSE)) %>% 
  prettify_names(.) %>% 
  mutate(any_ssi =  (postop_ssi_super + postop_ssi_deep + 	postop_ssi_organspace) > 1)
```

```{r insurance_analysis, warning = FALSE, message = FALSE}
insurance_df = 
  select(tidy_colectomies, any_ssi, postop_ssi_super,
                      postop_ssi_deep, postop_ssi_organspace,
                      insurance_payment_type) %>% 
  mutate(all_ssi = 
           postop_ssi_super + postop_ssi_deep + postop_ssi_organspace, 
         ssi = ifelse(all_ssi != 0, 1, 0),
         insurance_payment_type = as.factor(insurance_payment_type))
```

```{r insurance_plot, warning = FALSE}
ggplot(data = insurance_df,
                        aes(x = insurance_payment_type,
                            y = ssi,
                            fill = insurance_payment_type)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  labs(
    x = "Insurance Payment Type",
    y = "SSI",
    title = "Insurance Types and SSI"
  )
```

