---
title: "Project Proposal"
date: "11/5/2018"
output: github_document
---

# Group Members:

* Justin Hsie (UNI: jih2119)
* Xiao Shi (UNI: xs2330)
* Tiffany Tu (UNI: tt2714)
* Christian Pascual (UNI: cbp2128)

# Project Title

Factors Contributing to Colectomy Outcomes (Wolverine Edition)

# Motivation

Colectomies are a common surgery in the United States, but are also associated with a number of unpleasant patient outcomes. We have data on colectomies from 70 hospitals in Michigan, and we'd like to uncover which factors contribute to the success or failure of this invasive surgery. Uncovering these factors may help hospitals assess which patients may need more resources for successful surgery. 

# Intended final products

For our project, we will create:

* an interactive website detailing different linear regressions and interpretations OR
* an interactive website detailing geolocation of best hospitals in area, based on patient input
* a final model that has most significant factors contributes to a good (or bad) outcome

# Anticipated data sources

Our data comes from a course from the University of Michigan Department of Statistics, Statistical Consulting (Stats 504). Prior approval has been given to use the data for this project.

# Planned analyses, visualizations, coding

* Coding for interactive website
* Coding for modelling (testing for different models)
* Subanalyses:
  * Handling missing data
  * Checking correlation between variables
  * Tests if specific factors contribute to success or failure
  * try to demonstrate clustering for a visualization

# Planned timeline

Deliverable | Ideal Deadline | Hard Deadline
-----|-----|-----
Project proposal | November 7 | November 8
Project review meeting | N/A | November 12 - 16
Storyboarding website | Post-Review Meeting | November 12 - 16
Finalize analyses to-do | Post-Review Meeting | November 12 - 16
Report sub-analyses | November 23 | December 6
Report visualizations | November 23 | December 6
Report writing | November 23 | December 6
Polish graphs | November 27 | December 6
Polish report | November 27 | December 6
Finish web page | December 4 | December 6
Finish screencast | December 4 | December 6
Peer assessment | December 6 | December 6
