---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
    vertical_layout: fill
runtime: shiny
---

```{r lib-imports, include = FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)
library(shinyWidgets)
source("./utils.R")
```

```{r data-preparation }
colectomies = read.csv(file = './procedure10.csv') %>% 
  select(-starts_with("flg_"), -starts_with("e_")) %>% 
  select_if(unlist(map(., is_mostly_intact), use.names = FALSE)) %>% 
  prettify_names(.)
```


Row {.sidebar}
-----------------------------------------------------------------------

Think you can create a model that can predict a colectomy's success? Pick some predictors below to see if you can create a good model.

```{r model-covariates }
disease_states = c("diabetes", "dvt", "asthma")
patient_states = c("Uninsured", "Asian", "Latino")

# Delay all updates to charts until user is ready
# submitButton(text = "Regress!")

# Covariates for patient information states
pickerInput(
  inputId = "patientStates", 
  label = "Possible disease states", 
  choices = patient_states, 
  options = list(
    `actions-box` = TRUE, 
    size = 12,
    `selected-text-format` = "count > 3"
  ), 
  multiple = TRUE
)

# Covariates for disease states
pickerInput(
  inputId = "diseaseStates", 
  label = "Possible disease states", 
  choices = disease_states, 
  options = list(
    `actions-box` = TRUE, 
    size = 10,
    `selected-text-format` = "count > 3"
  ), 
  multiple = TRUE
)

```

Row {data-width=650}
-----------------------------------------------------------------------

### Model Information

```{r}
renderPrint({
  input[[diseaseStates]]
})
```

Row {data-width=350}
-----------------------------------------------------------------------

### Confidence Intervals

```{r}
tabsetPanel(
    tabPanel("Confidence Interval",verbatimTextOutput("summary")),
    tabPanel("Covariate Significance", verbatimTextOutput("summary"))
  )
```

### Predictive Value

```{r}
renderText({
  textOutput("patient_states")
})
```