---
title: "tiff_subanalysis"
author: "Tiffany Tu"
date: "11/25/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
source("./utils.R")

colectomies = read.csv(file = './procedure10.csv') 

is_mostly_intact = function(col) {
  # Account for literal NAs and blanks
  missings = is.na(col) | col == "" | col == "NA"
  return(sum(missings) <= (3084 / 2))
}

tidy_colectomies = colectomies %>% 
  select(-starts_with("flg_"), -starts_with("e_")) %>% 
  select_if(unlist(map(., is_mostly_intact), use.names = FALSE))

prettify_names(tidy_colectomies)
```

## How are successes distributed by patients with different diseases?

* Success can be measured by Surgical Site Infection (SSI) levels
  - postop_ssi_super	
  - postop_ssi_deep	
  - postop_ssi_organspace
* Types of prior diseases, disorder, or conditions

```{r}
healthdisease = tidy_colectomies %>% 
  select(death, ascites, bleeding_disorder, body_weight_loss, 
         chf, copd, chronic_condition, coronary_artery,
         diabetes, dialysis, disseminated_cancer, dvt,
         family_dvt, hypertension, peripheral_vascular_disease,
         pneumonia, preop_sepsis, preop_transfusion,
         sleep_apnea, smoker, etoh, ventilator, beta_blocker, 
         heparinbid, heparintid, skin_antisepsis, epidural_use, 
         indwelling_catheter, scd)
```

