---
title: "Colectomy Factors"
output: github_document
---
###Long term outcomes:

* HRQL (Health Related Quality of Life) - Majority reported increased HRQL (84%)

* 93% experienced some kind of functional restriction in work, social, physical, or sexual life after surgery

* Overall HRQL more important than individual 

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4628015/

###Complications in Colorectal Surgery

####Preoperative Risk Factors:

#####Non-influenceable risk factors:
* Age

* Gender

* Prior abdominal surgery

* Adhesion formation (irregular scar tissue)

* Comorbidity (2 chronic diseases/conditions)

* Emergency surgery

* Body weight loss

#####Influenceable risk factors:
* Obesity

* Nutritional Status

* Preoperative bowel cleaning

* Preoperative anemia

#####Intraoperative Risk Factors:

* Open/laparoscopic access to abdominal cavity

* Iatrogenic injuries (illness caused by medical exam/treatment)

* Surgical instruments

* Intraoperative blood loss

* Conversion(switching to open surgery)

* Operating time

####Postoperative Risk Factors:

* Postoperative analgesia (pain control)

* Postoperative diet

####Complications

* SSI

* Anastomotic leakage (connecting tubes, most serious)

* Postoperative bleeding

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2852382/


###FTR events (failure to rescue)

Deaths following: 

* Venous thromboembolism (vte) encompasses: Deep vein thrombosis (dvt) and pulmonary embolism (pe)

* Sepsis

* Gastrointestinal bleed

* Acute myocardial infarction

* Acute kidney injury

* Pneumonia

* Respiratory failure

* Shock

https://www.ncbi.nlm.nih.gov/pubmed/27765178

###Prevention of SSI

* Prehospitalization cleansing of Surgical Site

* Prolonged Preoperative Hospitalization (bad)

* Hair removal

* Plastic Drapes/Wound sealants (bad)

* Preventative antibiotics

* Antibacterial Suture

* Delayed primary closure


https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3881664/

###Risk Factors for SSI

Predicting SSIs:

* ASA score 

* Blood transfusion

* Creation of ostomy

* Use of drainage

* Sex

* Surgeons

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1422004/

###Other

* Left or right sided colectomy

* Length of stay
